In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/data.csv")

In [ ]:
df.describe()

year    customer_id         age  no_of_days_subscribed  \
count  2000.0    2000.000000  2000.00000            2000.000000   
mean   2015.0  554887.157500    38.69050              99.750000   
std       0.0  261033.690318    10.20641              39.755386   
min    2015.0  100198.000000    18.00000               1.000000   
25%    2015.0  328634.750000    32.00000              73.000000   
50%    2015.0  567957.500000    37.00000              99.000000   
75%    2015.0  773280.250000    44.00000             127.000000   
max    2015.0  999961.000000    82.00000             243.000000   

       weekly_mins_watched  minimum_daily_mins  maximum_daily_mins  \
count          2000.000000         2000.000000         2000.000000   
mean            270.178425           10.198700           30.620780   
std              80.551627            2.785519            9.129165   
min               0.000000            0.000000            0.000000   
25%             218.212500            8.400000           24.735000   
50%             269.925000           10.200000           30.590000   
75%             324.675000           12.000000           36.797500   
max             526.200000           20.000000           59.640000   

       weekly_max_night_mins  videos_watched  maximum_days_inactive  \
count            2000.000000     2000.000000            1972.000000   
mean              100.415500        4.482500               3.250507   
std                19.529454        2.487728               0.809084   
min                42.000000        0.000000               0.000000   
25%                87.000000        3.000000               3.000000   
50%               101.000000        4.000000               3.000000   
75%               114.000000        6.000000               4.000000   
max               175.000000       19.000000               6.000000   

       customer_support_calls        churn  
count             2000.000000  1965.000000  
mean                 1.547000     0.133333  
std                  1.315164     0.340021  
min                  0.000000     0.000000  
25%                  1.000000     0.000000  
50%                  1.000000     0.000000  
75%                  2.000000     0.000000  
max                  9.000000     1.000000

In [ ]:
df.head(10)

year  customer_id  phone_no  gender  age  no_of_days_subscribed  \
0  2015       100198  409-8743  Female   36                     62   
1  2015       100643  340-5930  Female   39                    149   
2  2015       100756  372-3750  Female   65                    126   
3  2015       101595  331-4902  Female   24                    131   
4  2015       101653  351-8398  Female   40                    191   
5  2015       101953  329-6603     NaN   31                     65   
6  2015       103051  416-1845     NaN   54                     59   
7  2015       103225  348-7193  Female   40                     50   
8  2015       103408  413-4039    Male   61                    205   
9  2015       103676  338-5207    Male   31                     63   

  multi_screen mail_subscribed  weekly_mins_watched  minimum_daily_mins  \
0           no              no               148.35                12.2   
1           no              no               294.45                 7.7   
2           no              no                87.30                11.9   
3           no             yes               321.30                 9.5   
4           no              no               243.00                10.9   
5           no              no               193.65                12.7   
6           no              no               239.25                10.2   
7           no              no               196.65                 5.6   
8           no             yes               263.70                 7.8   
9           no              no               316.80                12.3   

   maximum_daily_mins  weekly_max_night_mins  videos_watched  \
0               16.81                     82               1   
1               33.37                     87               3   
2                9.89                     91               1   
3               36.41                    102               4   
4               27.54                     83               7   
5               21.95                    111               6   
6               27.12                    106               4   
7               22.29                     88               9   
8               29.89                     64               5   
9               35.90                     58               2   

   maximum_days_inactive  customer_support_calls  churn  
0                    4.0                       1    0.0  
1                    3.0                       2    0.0  
2                    4.0                       5    1.0  
3                    3.0                       3    0.0  
4                    3.0                       1    0.0  
5                    4.0                       4    1.0  
6                    NaN                       0    0.0  
7                    NaN                       5    1.0  
8                    3.0                       2    0.0  
9                    4.0                       0    0.0

In [ ]:
df['multi_screen'].value_counts()

no     1802
yes     198
Name: multi_screen, dtype: int64

In [ ]:
df['mail_subscribed'].value_counts()

no     1430
yes     570
Name: mail_subscribed, dtype: int64

In [ ]:
# Dropping unwanted columns-customer_id,phone_no,gender

In [ ]:
df.drop(['year','customer_id','phone_no','gender'],axis=1,inplace=True)

In [ ]:
df.head()

age  no_of_days_subscribed multi_screen mail_subscribed  \
0   36                     62           no              no   
1   39                    149           no              no   
2   65                    126           no              no   
3   24                    131           no             yes   
4   40                    191           no              no   

   weekly_mins_watched  minimum_daily_mins  maximum_daily_mins  \
0               148.35                12.2               16.81   
1               294.45                 7.7               33.37   
2                87.30                11.9                9.89   
3               321.30                 9.5               36.41   
4               243.00                10.9               27.54   

   weekly_max_night_mins  videos_watched  maximum_days_inactive  \
0                     82               1                    4.0   
1                     87               3                    3.0   
2                     91               1                    4.0   
3                    102               4                    3.0   
4                     83               7                    3.0   

   customer_support_calls  churn  
0                       1    0.0  
1                       2    0.0  
2                       5    1.0  
3                       3    0.0  
4                       1    0.0

In [ ]:
df.shape

(2000, 12)

In [ ]:
df['age'].nunique()

63

In [ ]:
#Converting categorical data into numerical data

In [ ]:
answer = {"yes": 0, "no": 1}
df['multi_screen']=df['multi_screen'].map(answer)

In [ ]:
answer = {"yes": 0, "no": 1}
df['mail_subscribed']=df['mail_subscribed'].map(answer)

In [ ]:
df.head()

age  no_of_days_subscribed  multi_screen  mail_subscribed  \
0   36                     62             1                1   
1   39                    149             1                1   
2   65                    126             1                1   
3   24                    131             1                0   
4   40                    191             1                1   

   weekly_mins_watched  minimum_daily_mins  maximum_daily_mins  \
0               148.35                12.2               16.81   
1               294.45                 7.7               33.37   
2                87.30                11.9                9.89   
3               321.30                 9.5               36.41   
4               243.00                10.9               27.54   

   weekly_max_night_mins  videos_watched  maximum_days_inactive  \
0                     82               1                    4.0   
1                     87               3                    3.0   
2                     91               1                    4.0   
3                    102               4                    3.0   
4                     83               7                    3.0   

   customer_support_calls  churn  
0                       1    0.0  
1                       2    0.0  
2                       5    1.0  
3                       3    0.0  
4                       1    0.0

In [ ]:
df.isnull().sum()

age                        0
no_of_days_subscribed      0
multi_screen               0
mail_subscribed            0
weekly_mins_watched        0
minimum_daily_mins         0
maximum_daily_mins         0
weekly_max_night_mins      0
videos_watched             0
maximum_days_inactive     28
customer_support_calls     0
churn                     35
dtype: int64

In [ ]:
df['maximum_days_inactive'].value_counts()

3.0    945
4.0    645
2.0    273
5.0     85
1.0     12
0.0     10
6.0      2
Name: maximum_days_inactive, dtype: int64

In [ ]:
df['churn'].value_counts()

0.0    1703
1.0     262
Name: churn, dtype: int64

In [ ]:
#Filling missing values

In [ ]:
df['maximum_days_inactive'].median()

3.0

In [ ]:
df['maximum_days_inactive'].fillna(df['maximum_days_inactive'].median(),inplace=True)

In [ ]:
df['churn'].mode()

0    0.0
Name: churn, dtype: float64

In [ ]:
df['churn'].dtype

dtype('float64')

In [ ]:
df['churn'].fillna(0.0,inplace=True)

In [ ]:
df.isnull().sum()

age                       0
no_of_days_subscribed     0
multi_screen              0
mail_subscribed           0
weekly_mins_watched       0
minimum_daily_mins        0
maximum_daily_mins        0
weekly_max_night_mins     0
videos_watched            0
maximum_days_inactive     0
customer_support_calls    0
churn                     0
dtype: int64

In [ ]:
df.head()

age  no_of_days_subscribed  multi_screen  mail_subscribed  \
0   36                     62             1                1   
1   39                    149             1                1   
2   65                    126             1                1   
3   24                    131             1                0   
4   40                    191             1                1   

   weekly_mins_watched  minimum_daily_mins  maximum_daily_mins  \
0               148.35                12.2               16.81   
1               294.45                 7.7               33.37   
2                87.30                11.9                9.89   
3               321.30                 9.5               36.41   
4               243.00                10.9               27.54   

   weekly_max_night_mins  videos_watched  maximum_days_inactive  \
0                     82               1                    4.0   
1                     87               3                    3.0   
2                     91               1                    4.0   
3                    102               4                    3.0   
4                     83               7                    3.0   

   customer_support_calls  churn  
0                       1    0.0  
1                       2    0.0  
2                       5    1.0  
3                       3    0.0  
4                       1    0.0

In [ ]:
from sklearn.model_selection  import train_test_split

In [ ]:
x=df.drop(['churn'],axis=1)
y=df['churn']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,stratify=y,test_size=0.2)

In [ ]:
x_train.shape,y_train.shape

((1600, 11), (1600,))

In [ ]:
x_test.shape,y_test.shape

((400, 11), (400,))

In [ ]:
y_train.value_counts()

0.0    1390
1.0     210
Name: churn, dtype: int64

In [ ]:
y_test.value_counts()

0.0    348
1.0     52
Name: churn, dtype: int64

In [ ]:
from sklearn.linear_model import LinearRegression,LogisticRegression, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_validate

In [ ]:
#Linear Regression

In [ ]:
lnr = LinearRegression()
lnr.fit(x_train, y_train)
pred = lnr.predict(x_test)

error1 = mean_squared_error(y_test, pred)
print(error1)

0.09637617794673643


In [ ]:
cv = cross_validate(lnr, x_train, y_train, scoring = "neg_mean_squared_error", cv=5)
print(-cv['test_score'])

[0.08639597 0.10128196 0.09569157 0.10637268 0.10699096]


In [ ]:
#Logistic Regression

In [ ]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
pred1 = lr.predict(x_test)

acc1 = accuracy_score(y_test, pred1)
cm1=confusion_matrix(y_test,pred1)
ps1=precision_score(y_test,pred1)
rs1=recall_score(y_test,pred1)
print(acc1)
print(cm1)
print(ps1)
print(rs1)

0.865
[[339   9]
 [ 45   7]]
0.4375
0.1346153846153846


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
from sklearn.model_selection import cross_validate

cv1 = cross_validate(lr, x_train, y_train, scoring = "accuracy", cv=5)
cv1['test_score']

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.875   , 0.878125, 0.875   , 0.8625  , 0.846875])

In [ ]:
#Lasso Regression

In [ ]:
ls = Lasso()
ls.fit(x_train, y_train)
pred2 = ls.predict(x_test)

error2 = mean_squared_error(y_test, pred2)
print(error2)

0.11187182982060577


In [ ]:
cv2 = cross_validate(ls, x_train, y_train, scoring = "neg_mean_squared_error", cv=5)
print(-cv2['test_score'])

[0.10329257 0.11321368 0.10519502 0.12052785 0.1134633 ]


In [ ]:
#KNN

In [ ]:
# linscores = cross_validate(knn, x_train, y_train, scoring="neg_mean_squared_error", cv =5, return_estimator=True)
# cv_score_of_model = -1* (linscores['test_score'].mean())
score = {}
for i in range(1,10):
  knncv = KNeighborsRegressor(n_neighbors=i)
  linscores = cross_validate(knncv, x_train, y_train, scoring="neg_mean_squared_error", cv =5, return_estimator=True)
  cvscore = -1* (linscores['test_score'].mean())
  score[i] = cvscore
score

{1: 0.196875,
 2: 0.15218749999999998,
 3: 0.13541666666666669,
 4: 0.1267578125,
 5: 0.12057500000000002,
 6: 0.11727430555555556,
 7: 0.11559948979591836,
 8: 0.11345703124999999,
 9: 0.11314043209876545}

In [ ]:
best_k = [key for (key,value) in score.items() if value == min(score.values())][0]
best_k

9

In [ ]:
knn = KNeighborsRegressor(n_neighbors=9)
knn.fit(x_train, y_train)
pred3 = knn.predict(x_test)

error3 = mean_squared_error(y_test, pred3)
print(error3)

0.11219135802469136


In [ ]:
#SVC

In [ ]:
svc = SVC()
svc.fit(x_train, y_train)
pred4 = svc.predict(x_test)

acc2 =accuracy_score(y_test, pred4)
cm2=confusion_matrix(y_test,pred4)
ps2=precision_score(y_test,pred4)
rs2=recall_score(y_test,pred4)
print(acc2)
print(cm2)
print(ps2)
print(rs2)

0.87
[[348   0]
 [ 52   0]]
0.0
0.0


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.model_selection import cross_validate

cv3 = cross_validate(svc, x_train, y_train, scoring = "accuracy", cv=5)
cv3['test_score']

array([0.86875, 0.86875, 0.86875, 0.86875, 0.86875])

In [ ]:
#Decision Tree

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion' : ['gini', 'entropy'],
              'min_samples_split' : [2,3,4,5,6,7,8,9,12,14],
              'max_depth' : [3,4,5,6,7,8,9,10,12,14,16,18,20]
             }
tree_clas = DecisionTreeClassifier(random_state=1024)
grid_search = GridSearchCV(estimator=tree_clas, scoring = "accuracy", param_grid=param_grid, cv=5, verbose=True, n_jobs=-1)
grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 260 candidates, totalling 1300 fits


GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=1024),
             n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16, 18,
                                       20],
                         'min_samples_split': [2, 3, 4, 5, 6, 7, 8, 9, 12, 14]},
             scoring='accuracy', verbose=True)

In [ ]:
grid_search.best_estimator_

DecisionTreeClassifier(max_depth=8, min_samples_split=4, random_state=1024)

In [ ]:
dtc = DecisionTreeClassifier(random_state=1024, max_depth =8, min_samples_split=4)
dtc.fit(x_train, y_train)
train_pred1 = dtc.predict(x_train)
pred5 = dtc.predict(x_test)

acc3 = accuracy_score(y_test, pred5)
cm3=confusion_matrix(y_test,pred5)
ps3=precision_score(y_test,pred5)
rs3=recall_score(y_test,pred5)
print(acc3)
print(cm3)
print(ps3)
print(rs3)

0.9075
[[331  17]
 [ 20  32]]
0.6530612244897959
0.6153846153846154


In [ ]:
cv4 = cross_validate(dtc, x_train, y_train, scoring = "accuracy", cv=5)
print(cv4['test_score'])

[0.9125   0.903125 0.9125   0.915625 0.90625 ]


In [ ]:
#Random Forest

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

params = {"max_depth": range(2,25),
          "min_samples_split": range(2,15),
          "criterion":['gini','entropy']
          }

clf = RandomizedSearchCV(tree_clas, params, random_state=0, n_iter=200, scoring="accuracy", cv=4, n_jobs=-1)

clf.fit(x_train, y_train)

RandomizedSearchCV(cv=4, estimator=DecisionTreeClassifier(random_state=1024),
                   n_iter=200, n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': range(2, 25),
                                        'min_samples_split': range(2, 15)},
                   random_state=0, scoring='accuracy')

In [ ]:
clf.best_params_

{'min_samples_split': 2, 'max_depth': 5, 'criterion': 'entropy'}

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf = RandomForestClassifier(n_estimators = 100)
rf.fit(x_train, y_train)
train_pred2 = rf.predict(x_train)
pred6 = rf.predict(x_test)

acc4 = accuracy_score(y_test, pred6)
cm4=confusion_matrix(y_test,pred6)
ps4=precision_score(y_test,pred6)
rs4=recall_score(y_test,pred6)
print(acc4)
print(cm4)
print(ps4)
print(rs4)

0.94
[[342   6]
 [ 18  34]]
0.85
0.6538461538461539


In [ ]:
cv5 = cross_validate(rf, x_train, y_train, scoring = "accuracy", cv=5)
print(cv5['test_score'])

[0.90625  0.909375 0.93125  0.9375   0.903125]


In [ ]:
# From the recall score,precison score,accuracy score and confusion matrix of each algortihm we can clearly
# see that the Random Forest algorithm is the best suited for this data'

In [ ]:
rf.predict(x_test)

array([1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 0., 0.